apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: belleshop-backend-monitor
  namespace: dev
  labels:
    release: prometheus-stack
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      scrapeTimeout: 10s
