apiVersion: v1
kind: Secret
metadata:
  name: gitea-belleshop-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitea.stratdevs.com/tunsgit/BelleShop.git
  username: tunsgit
  password: 534efec562a2f69a51f33c13fa65cbab82441bfc
