apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    canary:
      stableService: backend
      canaryService: backend-canary
      trafficRouting:
        nginx:
          stableIngress: belleshop-api-ingress
      steps:
        # Step 1: Route 10% traffic to Canary
        - setWeight: 10
        - pause: { duration: 15s }
        # Step 2: Route 50% traffic to Canary
        - setWeight: 50
        - pause: { duration: 15s }
        # Step 3: Analyze Prometheus Error Rates before final 100% promotion
        - analysis:
            templates:
              - templateName: success-rate
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: backend
          image: belleshop-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: belleshop-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: belleshop-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: belleshop-secrets
                  key: MYSQL_DATABASE
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: belleshop-secrets
                  key: SECRET_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
