apiVersion: v1
kind: Secret
metadata:
  name: belleshop-secrets
  namespace: dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "password"
  MYSQL_DATABASE: "belle_shop"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "password"
  SECRET_KEY: "supersecretkey"
